# Generated by Django 4.1.7 on 2023-07-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.TextField(max_length=12)),
                ('aadhar_no', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PANdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.TextField(max_length=12)),
                ('pan_no', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
