# Generated by Django 4.1.7 on 2023-07-29 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_issueddoc_alter_aadhaardetails_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueddoc',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
