# Generated by Django 4.1.7 on 2023-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_issueddoc_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueddoc',
            name='gender',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='pandetails',
            name='gender',
            field=models.CharField(max_length=12),
        ),
    ]
