# Generated by Django 4.1.7 on 2023-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_issueddoc_gender_alter_pandetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueddoc',
            name='dob',
            field=models.CharField(max_length=10),
        ),
    ]
