# Generated by Django 4.1.7 on 2023-07-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_issueddoc_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='firstname',
            new_name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='details',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='details',
            name='lastname',
        ),
    ]
